spring:
  session:
      store-type: redis
  data:
    redis:
      host: 127.0.0.1
      port: 6369
  datasource:
    url: jdbc:mysql://127.0.0.1:3305/fastsns
    username: root
    password: qwer1234
  jpa:
    hibernate.ddl-auto: create
    show-sql: true

